# Generated by Django 4.2 on 2023-04-11 23:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(
                    choices=[('SwapSale', 'SwapSale'), ('NewUser', 'NewUser'), ('UpdateUser', 'UpdateUser'),
                             ('MembershipSale', 'MembershipSale')], max_length=100)),
                ('payload', models.JSONField()),
                ('timestamp', models.DateTimeField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
