# Generated by Django 4.2 on 2023-06-07 22:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('webhooks', '0002_alter_webhook_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='webhook',
            table='webhooks',
        ),
    ]
