# Generated by Django 4.2 on 2023-04-11 15:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('hubs', '0002_alter_hub_device_id'),
        ('customers', '0010_alter_customer_guarantor_phone_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('pack_id', models.CharField(max_length=9, primary_key=True, serialize=False, validators=[
                    django.core.validators.RegexValidator('^[0-9]{9}$', 'Pack ID must have 9 digits')])),
                ('pack_status', models.CharField(
                    choices=[('AtHubUncharged', 'AtHubUncharged'), ('AtHubCharged', 'AtHubCharged'),
                             ('SignedOut', 'SignedOut'), ('Charging', 'Charging'), ('Defective', 'Defective'),
                             ('Lost', 'Lost')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_customer',
                 models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   to='customers.customer')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubs.hub')),
            ],
        ),
    ]
