# Generated by Django 4.2 on 2023-04-11 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('customers', '0004_alter_customer_guarantor_phone_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='customers.customer')),
                ('is_active', models.BooleanField(default=True)),
                ('pin', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'staffs',
            },
        ),
    ]
