# Generated by Django 4.2 on 2023-04-11 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customers', '0005_alter_customer_guarantor_phone_alter_customer_phone'),
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                       serialize=False, to='customers.customer'),
        ),
    ]
