# Generated by Django 4.2 on 2023-04-11 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('staffs', '0003_alter_staff_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='user',
            new_name='customer',
        ),
    ]
