# Generated by Django 4.2 on 2023-04-11 10:13

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import customers.fields
import customers.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', customers.fields.PhoneNumberField(max_length=50, validators=[
                    django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must have 10 digits'),
                    customers.validators.validate_phone_number,
                    django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must have 10 digits'),
                    customers.validators.validate_phone_number])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantor_first_name', models.CharField(max_length=50)),
                ('guarantor_last_name', models.CharField(max_length=50)),
                ('guarantor_phone', customers.fields.PhoneNumberField(max_length=50, validators=[
                    django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must have 10 digits'),
                    customers.validators.validate_phone_number,
                    django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must have 10 digits'),
                    customers.validators.validate_phone_number])),
                ('membership_expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubs.hub')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
