# Generated by Django 4.2 on 2023-04-11 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('packs', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pack_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='transactions_in', to='packs.pack'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pack_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='transactions_out', to='packs.pack'),
        ),
    ]
